[package]
name = "chadlang"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"

error_handling = { path = "src/error_handling" }
lexer = { path = "src/lexer" }
